### PR TITLE
GvG cards Mana key problem

### PR DESCRIPTION
**Pull request by ulasbilgen**
GvG cards had "cost" as "mana" key. Replaced all the "cost" with "mana"

### CODE REVIEW

**Comment by pdyck** [comment]
Thanks!

**Comment by ulasbilgen** [comment]
No problem,

Actually 2 cards are missing also, I’ll add them later on. The missing cards are “Gelbin Mekkatorque” and “Elite Tauren Chieftain”. Did add them yet cause I don’t know how you give the IDs to the cards :)

Cheers,

Ulas

**Comment by pdyck** [comment]
I actually don't have a real system. I just used IDs in the 1000 range for the old cards and 2000 for everything after Naxx.

So for Gelbin and Chieftain you could use anything between 1738 and 1999 since those won't be used anyways.

**Comment by ulasbilgen** [comment]
Cool I’’ll use 1738 and 1739 respectively :)

Cheers,

Ulas

**Comment by pdyck** [comment]
Thanks a lot!

**Pull request merged**
